// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: proto_option.proto

package messageoption

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ==============================================================================
// 节点类型定义（所有服务节点的类型标识）
// ==============================================================================
type NodeType int32

const (
	// 基础类型
	NodeType_NODE_UNSPECIFIED NodeType = 0 // 默认值（未指定）
	NodeType_NODE_CLIENT      NodeType = 1 // 客户端节点
	// 核心服务节点
	NodeType_NODE_GATE       NodeType = 2 // 网关服节点
	NodeType_NODE_ROOM       NodeType = 3 // 房间服节点
	NodeType_NODE_CENTRE     NodeType = 4 // 中心服节点
	NodeType_NODE_DB         NodeType = 5 // 数据库节点
	NodeType_NODE_DEPLOY     NodeType = 6 // 部署节点服务
	NodeType_NODE_DB_SERVICE NodeType = 7 // 数据库节点服务
	// 游戏业务节点
	NodeType_NODE_CENTRE_SCENE NodeType = 8  // 场景切换中心服务器服务
	NodeType_NODE_SCENE        NodeType = 9  // 场景服务器服务
	NodeType_NODE_LOGIN        NodeType = 10 // 登录服务器节点服务
	NodeType_NODE_MAIL         NodeType = 13 // 邮件节点服务
	NodeType_NODE_CHAT         NodeType = 14 // 聊天节点服务
	NodeType_NODE_TEAM         NodeType = 15 // 组队节点服务
	NodeType_NODE_ACTIVITY     NodeType = 16 // 活动节点服务
	NodeType_NODE_TRADE        NodeType = 17 // 玩家交易或拍卖行服务
	NodeType_NODE_RANK         NodeType = 18 // 排行榜服务
	NodeType_NODE_TASK         NodeType = 19 // 任务系统服务
	NodeType_NODE_GUILD        NodeType = 20 // 公会系统服务
	NodeType_NODE_MATCH        NodeType = 21 // 匹配系统服务（如组队副本、PVP等）
	NodeType_NODE_AI           NodeType = 22 // AI/NPC 控制服务
	// 基础设施节点
	NodeType_NODE_REDIS          NodeType = 11 // Redis 节点服务
	NodeType_NODE_ETCD           NodeType = 12 // etcd节点
	NodeType_NODE_LOG            NodeType = 23 // 日志处理/收集服务
	NodeType_NODE_PAYMENT        NodeType = 24 // 支付或充值服务
	NodeType_NODE_SECURITY       NodeType = 25 // 反作弊/安全验证服务
	NodeType_NODE_CROSS_SERVER   NodeType = 26 // 跨服服务处理（如跨服战场）
	NodeType_NODE_ANALYTICS      NodeType = 27 // 数据统计与分析服务
	NodeType_NODE_GM             NodeType = 28 // GM工具服务（客服/管理员指令）
	NodeType_NODE_PLAYER_LOCATOR NodeType = 29 // 跨服玩家定位服务
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0:  "NODE_UNSPECIFIED",
		1:  "NODE_CLIENT",
		2:  "NODE_GATE",
		3:  "NODE_ROOM",
		4:  "NODE_CENTRE",
		5:  "NODE_DB",
		6:  "NODE_DEPLOY",
		7:  "NODE_DB_SERVICE",
		8:  "NODE_CENTRE_SCENE",
		9:  "NODE_SCENE",
		10: "NODE_LOGIN",
		13: "NODE_MAIL",
		14: "NODE_CHAT",
		15: "NODE_TEAM",
		16: "NODE_ACTIVITY",
		17: "NODE_TRADE",
		18: "NODE_RANK",
		19: "NODE_TASK",
		20: "NODE_GUILD",
		21: "NODE_MATCH",
		22: "NODE_AI",
		11: "NODE_REDIS",
		12: "NODE_ETCD",
		23: "NODE_LOG",
		24: "NODE_PAYMENT",
		25: "NODE_SECURITY",
		26: "NODE_CROSS_SERVER",
		27: "NODE_ANALYTICS",
		28: "NODE_GM",
		29: "NODE_PLAYER_LOCATOR",
	}
	NodeType_value = map[string]int32{
		"NODE_UNSPECIFIED":    0,
		"NODE_CLIENT":         1,
		"NODE_GATE":           2,
		"NODE_ROOM":           3,
		"NODE_CENTRE":         4,
		"NODE_DB":             5,
		"NODE_DEPLOY":         6,
		"NODE_DB_SERVICE":     7,
		"NODE_CENTRE_SCENE":   8,
		"NODE_SCENE":          9,
		"NODE_LOGIN":          10,
		"NODE_MAIL":           13,
		"NODE_CHAT":           14,
		"NODE_TEAM":           15,
		"NODE_ACTIVITY":       16,
		"NODE_TRADE":          17,
		"NODE_RANK":           18,
		"NODE_TASK":           19,
		"NODE_GUILD":          20,
		"NODE_MATCH":          21,
		"NODE_AI":             22,
		"NODE_REDIS":          11,
		"NODE_ETCD":           12,
		"NODE_LOG":            23,
		"NODE_PAYMENT":        24,
		"NODE_SECURITY":       25,
		"NODE_CROSS_SERVER":   26,
		"NODE_ANALYTICS":      27,
		"NODE_GM":             28,
		"NODE_PLAYER_LOCATOR": 29,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_option_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_proto_option_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_option_proto_rawDescGZIP(), []int{0}
}

// 数据操作类型
type OPERATE_TYPE int32

const (
	OPERATE_TYPE_OPERATE_NONE          OPERATE_TYPE = 0 //无操作
	OPERATE_TYPE_OPERATE_INSERT        OPERATE_TYPE = 1 //插入数据
	OPERATE_TYPE_OPERATE_UPDATE        OPERATE_TYPE = 2 //更新数据
	OPERATE_TYPE_OPERATE_DELETE        OPERATE_TYPE = 3 //删除数据
	OPERATE_TYPE_OPERATE_LOAD          OPERATE_TYPE = 4 //加载数据
	OPERATE_TYPE_OPERATE_DELETE_CACHE  OPERATE_TYPE = 5 //删除缓存
	OPERATE_TYPE_OPERATE_REPLACE       OPERATE_TYPE = 6 //替换数据
	OPERATE_TYPE_OPERATE_CALL_PROC     OPERATE_TYPE = 7 //调用存储过程
	OPERATE_TYPE_OPERATE_DELETE_BACKUP OPERATE_TYPE = 8 //删除备份
)

// Enum value maps for OPERATE_TYPE.
var (
	OPERATE_TYPE_name = map[int32]string{
		0: "OPERATE_NONE",
		1: "OPERATE_INSERT",
		2: "OPERATE_UPDATE",
		3: "OPERATE_DELETE",
		4: "OPERATE_LOAD",
		5: "OPERATE_DELETE_CACHE",
		6: "OPERATE_REPLACE",
		7: "OPERATE_CALL_PROC",
		8: "OPERATE_DELETE_BACKUP",
	}
	OPERATE_TYPE_value = map[string]int32{
		"OPERATE_NONE":          0,
		"OPERATE_INSERT":        1,
		"OPERATE_UPDATE":        2,
		"OPERATE_DELETE":        3,
		"OPERATE_LOAD":          4,
		"OPERATE_DELETE_CACHE":  5,
		"OPERATE_REPLACE":       6,
		"OPERATE_CALL_PROC":     7,
		"OPERATE_DELETE_BACKUP": 8,
	}
)

func (x OPERATE_TYPE) Enum() *OPERATE_TYPE {
	p := new(OPERATE_TYPE)
	*p = x
	return p
}

func (x OPERATE_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OPERATE_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_option_proto_enumTypes[1].Descriptor()
}

func (OPERATE_TYPE) Type() protoreflect.EnumType {
	return &file_proto_option_proto_enumTypes[1]
}

func (x OPERATE_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OPERATE_TYPE.Descriptor instead.
func (OPERATE_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_proto_option_proto_rawDescGZIP(), []int{1}
}

// 业务操作结果类型
type BS_RESULT_TYPE int32

const (
	BS_RESULT_TYPE_BS_RESULT_NONE    BS_RESULT_TYPE = 0 //无结果
	BS_RESULT_TYPE_BS_RESULT_SUCCESS BS_RESULT_TYPE = 1 //操作成功
	BS_RESULT_TYPE_BS_RESULT_FAILED  BS_RESULT_TYPE = 2 //操作失败
)

// Enum value maps for BS_RESULT_TYPE.
var (
	BS_RESULT_TYPE_name = map[int32]string{
		0: "BS_RESULT_NONE",
		1: "BS_RESULT_SUCCESS",
		2: "BS_RESULT_FAILED",
	}
	BS_RESULT_TYPE_value = map[string]int32{
		"BS_RESULT_NONE":    0,
		"BS_RESULT_SUCCESS": 1,
		"BS_RESULT_FAILED":  2,
	}
)

func (x BS_RESULT_TYPE) Enum() *BS_RESULT_TYPE {
	p := new(BS_RESULT_TYPE)
	*p = x
	return p
}

func (x BS_RESULT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BS_RESULT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_option_proto_enumTypes[2].Descriptor()
}

func (BS_RESULT_TYPE) Type() protoreflect.EnumType {
	return &file_proto_option_proto_enumTypes[2]
}

func (x BS_RESULT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BS_RESULT_TYPE.Descriptor instead.
func (BS_RESULT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_proto_option_proto_rawDescGZIP(), []int{2}
}

var file_proto_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*NodeType)(nil),
		Field:         200003,
		Name:          "OptionFileDefaultNode",
		Tag:           "varint,200003,opt,name=OptionFileDefaultNode,enum=NodeType",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         400000,
		Name:          "OptionIsPlayerService",
		Tag:           "varint,400000,opt,name=OptionIsPlayerService",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         400001,
		Name:          "OptionIsClientProtocolService",
		Tag:           "varint,400001,opt,name=OptionIsClientProtocolService",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         500000,
		Name:          "OptionTableId",
		Tag:           "varint,500000,opt,name=OptionTableId",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500001,
		Name:          "OptionTableName",
		Tag:           "bytes,500001,opt,name=OptionTableName",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500002,
		Name:          "OptionPrimaryKey",
		Tag:           "bytes,500002,opt,name=OptionPrimaryKey",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500003,
		Name:          "OptionForeignKey",
		Tag:           "bytes,500003,opt,name=OptionForeignKey",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500005,
		Name:          "OptionForeignReferences",
		Tag:           "bytes,500005,opt,name=OptionForeignReferences",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500006,
		Name:          "OptionAutoIncrementKey",
		Tag:           "bytes,500006,opt,name=OptionAutoIncrementKey",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500007,
		Name:          "OptionBackupTableName",
		Tag:           "bytes,500007,opt,name=OptionBackupTableName",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         500008,
		Name:          "OptionLoadOnly",
		Tag:           "varint,500008,opt,name=OptionLoadOnly",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500009,
		Name:          "OptionProcedureName",
		Tag:           "bytes,500009,opt,name=OptionProcedureName",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500010,
		Name:          "OptionProcedureResult",
		Tag:           "bytes,500010,opt,name=OptionProcedureResult",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500011,
		Name:          "OptionIndex",
		Tag:           "bytes,500011,opt,name=OptionIndex",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500012,
		Name:          "OptionUniqueKey",
		Tag:           "bytes,500012,opt,name=OptionUniqueKey",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         500013,
		Name:          "OptionIsPlayerDatabase",
		Tag:           "varint,500013,opt,name=OptionIsPlayerDatabase",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*OPERATE_TYPE)(nil),
		Field:         500014,
		Name:          "OptionOperateType",
		Tag:           "varint,500014,opt,name=OptionOperateType,enum=OPERATE_TYPE",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         700000,
		Name:          "OptionBaseAttributeSync",
		Tag:           "varint,700000,opt,name=OptionBaseAttributeSync",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         700001,
		Name:          "OptionDeltaAttributeSync",
		Tag:           "varint,700001,opt,name=OptionDeltaAttributeSync",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*uint32)(nil),
		Field:         600000,
		Name:          "OptionRepeatLimit",
		Tag:           "varint,600000,opt,name=OptionRepeatLimit",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         600001,
		Name:          "OptionDBFieldExtra",
		Tag:           "bytes,600001,opt,name=OptionDBFieldExtra",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         600002,
		Name:          "OptionDBReadOnly",
		Tag:           "varint,600002,opt,name=OptionDBReadOnly",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         600003,
		Name:          "OptionDBNamePrefix",
		Tag:           "bytes,600003,opt,name=OptionDBNamePrefix",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         600004,
		Name:          "OptionDBLoadSql",
		Tag:           "bytes,600004,opt,name=OptionDBLoadSql",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         600005,
		Name:          "OptionDBNeedEscape",
		Tag:           "varint,600005,opt,name=OptionDBNeedEscape",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         600006,
		Name:          "OptionDBProcParam",
		Tag:           "varint,600006,opt,name=OptionDBProcParam",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         600007,
		Name:          "OptionOldName",
		Tag:           "bytes,600007,opt,name=OptionOldName",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         600008,
		Name:          "OptionTable",
		Tag:           "bytes,600008,opt,name=OptionTable",
		Filename:      "proto_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         600009,
		Name:          "OptionBackUpTabel",
		Tag:           "bytes,600009,opt,name=OptionBackUpTabel",
		Filename:      "proto_option.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional NodeType OptionFileDefaultNode = 200003;
	E_OptionFileDefaultNode = &file_proto_option_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// 标记该服务是否是玩家相关服务（PlayerService）
	//
	// optional bool OptionIsPlayerService = 400000;
	E_OptionIsPlayerService = &file_proto_option_proto_extTypes[1]
	// 标记该服务是否是客户端协议服务（供客户端调用）
	//
	// optional bool OptionIsClientProtocolService = 400001;
	E_OptionIsClientProtocolService = &file_proto_option_proto_extTypes[2]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional uint32 OptionTableId = 500000;
	E_OptionTableId = &file_proto_option_proto_extTypes[3] //表ID
	// optional string OptionTableName = 500001;
	E_OptionTableName = &file_proto_option_proto_extTypes[4] //表名
	// optional string OptionPrimaryKey = 500002;
	E_OptionPrimaryKey = &file_proto_option_proto_extTypes[5] //主键
	// optional string OptionForeignKey = 500003;
	E_OptionForeignKey = &file_proto_option_proto_extTypes[6] //外键
	// optional string OptionForeignReferences = 500005;
	E_OptionForeignReferences = &file_proto_option_proto_extTypes[7] //外键的关联表
	// optional string OptionAutoIncrementKey = 500006;
	E_OptionAutoIncrementKey = &file_proto_option_proto_extTypes[8] //自增长的Key
	// optional string OptionBackupTableName = 500007;
	E_OptionBackupTableName = &file_proto_option_proto_extTypes[9] //备份表的名称
	// optional bool OptionLoadOnly = 500008;
	E_OptionLoadOnly = &file_proto_option_proto_extTypes[10] //只用于数据加载
	// optional string OptionProcedureName = 500009;
	E_OptionProcedureName = &file_proto_option_proto_extTypes[11] //存储过程名称
	// optional string OptionProcedureResult = 500010;
	E_OptionProcedureResult = &file_proto_option_proto_extTypes[12] //存储过程返回结果的PB结构Name
	// optional string OptionIndex = 500011;
	E_OptionIndex = &file_proto_option_proto_extTypes[13] //建立索引
	// optional string OptionUniqueKey = 500012;
	E_OptionUniqueKey = &file_proto_option_proto_extTypes[14] //唯一键
	// optional bool OptionIsPlayerDatabase = 500013;
	E_OptionIsPlayerDatabase = &file_proto_option_proto_extTypes[15] // 标识是否是玩家数据库
	// optional OPERATE_TYPE OptionOperateType = 500014;
	E_OptionOperateType = &file_proto_option_proto_extTypes[16]
	// ---------- 属性同步相关 ----------
	//
	// optional bool OptionBaseAttributeSync = 700000;
	E_OptionBaseAttributeSync = &file_proto_option_proto_extTypes[17] // 基础属性同步
	// optional bool OptionDeltaAttributeSync = 700001;
	E_OptionDeltaAttributeSync = &file_proto_option_proto_extTypes[18] // 增量属性同步
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional uint32 OptionRepeatLimit = 600000;
	E_OptionRepeatLimit = &file_proto_option_proto_extTypes[19] // repeat 字段限制的个数
	// optional string OptionDBFieldExtra = 600001;
	E_OptionDBFieldExtra = &file_proto_option_proto_extTypes[20] // 创建数据库要用到得额外信息，如果没有该属性表示非数据库字段
	// optional bool OptionDBReadOnly = 600002;
	E_OptionDBReadOnly = &file_proto_option_proto_extTypes[21] // 该字段对DB是否只读
	// optional string OptionDBNamePrefix = 600003;
	E_OptionDBNamePrefix = &file_proto_option_proto_extTypes[22] // 数据库名称前缀
	// optional string OptionDBLoadSql = 600004;
	E_OptionDBLoadSql = &file_proto_option_proto_extTypes[23] // 数据加载SQL语句
	// optional bool OptionDBNeedEscape = 600005;
	E_OptionDBNeedEscape = &file_proto_option_proto_extTypes[24] // 字段是否需要转义存储
	// optional bool OptionDBProcParam = 600006;
	E_OptionDBProcParam = &file_proto_option_proto_extTypes[25] // 是否存储过程参数
	// optional string OptionOldName = 600007;
	E_OptionOldName = &file_proto_option_proto_extTypes[26] //用来自动修改字段名
	// optional string OptionTable = 600008;
	E_OptionTable = &file_proto_option_proto_extTypes[27] // 建表名称
	// optional string OptionBackUpTabel = 600009;
	E_OptionBackUpTabel = &file_proto_option_proto_extTypes[28] //备份表
)

var File_proto_option_proto protoreflect.FileDescriptor

const file_proto_option_proto_rawDesc = "" +
	"\n" +
	"\x12proto_option.proto\x1a\x10descriptor.proto*\x88\x04\n" +
	"\bNodeType\x12\x14\n" +
	"\x10NODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vNODE_CLIENT\x10\x01\x12\r\n" +
	"\tNODE_GATE\x10\x02\x12\r\n" +
	"\tNODE_ROOM\x10\x03\x12\x0f\n" +
	"\vNODE_CENTRE\x10\x04\x12\v\n" +
	"\aNODE_DB\x10\x05\x12\x0f\n" +
	"\vNODE_DEPLOY\x10\x06\x12\x13\n" +
	"\x0fNODE_DB_SERVICE\x10\a\x12\x15\n" +
	"\x11NODE_CENTRE_SCENE\x10\b\x12\x0e\n" +
	"\n" +
	"NODE_SCENE\x10\t\x12\x0e\n" +
	"\n" +
	"NODE_LOGIN\x10\n" +
	"\x12\r\n" +
	"\tNODE_MAIL\x10\r\x12\r\n" +
	"\tNODE_CHAT\x10\x0e\x12\r\n" +
	"\tNODE_TEAM\x10\x0f\x12\x11\n" +
	"\rNODE_ACTIVITY\x10\x10\x12\x0e\n" +
	"\n" +
	"NODE_TRADE\x10\x11\x12\r\n" +
	"\tNODE_RANK\x10\x12\x12\r\n" +
	"\tNODE_TASK\x10\x13\x12\x0e\n" +
	"\n" +
	"NODE_GUILD\x10\x14\x12\x0e\n" +
	"\n" +
	"NODE_MATCH\x10\x15\x12\v\n" +
	"\aNODE_AI\x10\x16\x12\x0e\n" +
	"\n" +
	"NODE_REDIS\x10\v\x12\r\n" +
	"\tNODE_ETCD\x10\f\x12\f\n" +
	"\bNODE_LOG\x10\x17\x12\x10\n" +
	"\fNODE_PAYMENT\x10\x18\x12\x11\n" +
	"\rNODE_SECURITY\x10\x19\x12\x15\n" +
	"\x11NODE_CROSS_SERVER\x10\x1a\x12\x12\n" +
	"\x0eNODE_ANALYTICS\x10\x1b\x12\v\n" +
	"\aNODE_GM\x10\x1c\x12\x17\n" +
	"\x13NODE_PLAYER_LOCATOR\x10\x1d*\xcf\x01\n" +
	"\fOPERATE_TYPE\x12\x10\n" +
	"\fOPERATE_NONE\x10\x00\x12\x12\n" +
	"\x0eOPERATE_INSERT\x10\x01\x12\x12\n" +
	"\x0eOPERATE_UPDATE\x10\x02\x12\x12\n" +
	"\x0eOPERATE_DELETE\x10\x03\x12\x10\n" +
	"\fOPERATE_LOAD\x10\x04\x12\x18\n" +
	"\x14OPERATE_DELETE_CACHE\x10\x05\x12\x13\n" +
	"\x0fOPERATE_REPLACE\x10\x06\x12\x15\n" +
	"\x11OPERATE_CALL_PROC\x10\a\x12\x19\n" +
	"\x15OPERATE_DELETE_BACKUP\x10\b*Q\n" +
	"\x0eBS_RESULT_TYPE\x12\x12\n" +
	"\x0eBS_RESULT_NONE\x10\x00\x12\x15\n" +
	"\x11BS_RESULT_SUCCESS\x10\x01\x12\x14\n" +
	"\x10BS_RESULT_FAILED\x10\x02:_\n" +
	"\x15OptionFileDefaultNode\x12\x1c.google.protobuf.FileOptions\x18Ú\f \x01(\x0e2\t.NodeTypeR\x15OptionFileDefaultNode:W\n" +
	"\x15OptionIsPlayerService\x12\x1f.google.protobuf.ServiceOptions\x18\x80\xb5\x18 \x01(\bR\x15OptionIsPlayerService:g\n" +
	"\x1dOptionIsClientProtocolService\x12\x1f.google.protobuf.ServiceOptions\x18\x81\xb5\x18 \x01(\bR\x1dOptionIsClientProtocolService:J\n" +
	"\rOptionTableId\x12\x1f.google.protobuf.MessageOptions\x18\xa0\xc2\x1e \x01(\rR\rOptionTableId\x88\x01\x01:N\n" +
	"\x0fOptionTableName\x12\x1f.google.protobuf.MessageOptions\x18\xa1\xc2\x1e \x01(\tR\x0fOptionTableName\x88\x01\x01:P\n" +
	"\x10OptionPrimaryKey\x12\x1f.google.protobuf.MessageOptions\x18\xa2\xc2\x1e \x01(\tR\x10OptionPrimaryKey\x88\x01\x01:P\n" +
	"\x10OptionForeignKey\x12\x1f.google.protobuf.MessageOptions\x18\xa3\xc2\x1e \x01(\tR\x10OptionForeignKey\x88\x01\x01:^\n" +
	"\x17OptionForeignReferences\x12\x1f.google.protobuf.MessageOptions\x18\xa5\xc2\x1e \x01(\tR\x17OptionForeignReferences\x88\x01\x01:\\\n" +
	"\x16OptionAutoIncrementKey\x12\x1f.google.protobuf.MessageOptions\x18\xa6\xc2\x1e \x01(\tR\x16OptionAutoIncrementKey\x88\x01\x01:Z\n" +
	"\x15OptionBackupTableName\x12\x1f.google.protobuf.MessageOptions\x18\xa7\xc2\x1e \x01(\tR\x15OptionBackupTableName\x88\x01\x01:L\n" +
	"\x0eOptionLoadOnly\x12\x1f.google.protobuf.MessageOptions\x18\xa8\xc2\x1e \x01(\bR\x0eOptionLoadOnly\x88\x01\x01:V\n" +
	"\x13OptionProcedureName\x12\x1f.google.protobuf.MessageOptions\x18\xa9\xc2\x1e \x01(\tR\x13OptionProcedureName\x88\x01\x01:Z\n" +
	"\x15OptionProcedureResult\x12\x1f.google.protobuf.MessageOptions\x18\xaa\xc2\x1e \x01(\tR\x15OptionProcedureResult\x88\x01\x01:F\n" +
	"\vOptionIndex\x12\x1f.google.protobuf.MessageOptions\x18\xab\xc2\x1e \x01(\tR\vOptionIndex\x88\x01\x01:N\n" +
	"\x0fOptionUniqueKey\x12\x1f.google.protobuf.MessageOptions\x18\xac\xc2\x1e \x01(\tR\x0fOptionUniqueKey\x88\x01\x01:\\\n" +
	"\x16OptionIsPlayerDatabase\x12\x1f.google.protobuf.MessageOptions\x18\xad\xc2\x1e \x01(\bR\x16OptionIsPlayerDatabase\x88\x01\x01:a\n" +
	"\x11OptionOperateType\x12\x1f.google.protobuf.MessageOptions\x18\xae\xc2\x1e \x01(\x0e2\r.OPERATE_TYPER\x11OptionOperateType\x88\x01\x01:^\n" +
	"\x17OptionBaseAttributeSync\x12\x1f.google.protobuf.MessageOptions\x18\xe0\xdc* \x01(\bR\x17OptionBaseAttributeSync\x88\x01\x01:`\n" +
	"\x18OptionDeltaAttributeSync\x12\x1f.google.protobuf.MessageOptions\x18\xe1\xdc* \x01(\bR\x18OptionDeltaAttributeSync\x88\x01\x01:P\n" +
	"\x11OptionRepeatLimit\x12\x1d.google.protobuf.FieldOptions\x18\xc0\xcf$ \x01(\rR\x11OptionRepeatLimit\x88\x01\x01:R\n" +
	"\x12OptionDBFieldExtra\x12\x1d.google.protobuf.FieldOptions\x18\xc1\xcf$ \x01(\tR\x12OptionDBFieldExtra\x88\x01\x01:N\n" +
	"\x10OptionDBReadOnly\x12\x1d.google.protobuf.FieldOptions\x18\xc2\xcf$ \x01(\bR\x10OptionDBReadOnly\x88\x01\x01:R\n" +
	"\x12OptionDBNamePrefix\x12\x1d.google.protobuf.FieldOptions\x18\xc3\xcf$ \x01(\tR\x12OptionDBNamePrefix\x88\x01\x01:L\n" +
	"\x0fOptionDBLoadSql\x12\x1d.google.protobuf.FieldOptions\x18\xc4\xcf$ \x01(\tR\x0fOptionDBLoadSql\x88\x01\x01:R\n" +
	"\x12OptionDBNeedEscape\x12\x1d.google.protobuf.FieldOptions\x18\xc5\xcf$ \x01(\bR\x12OptionDBNeedEscape\x88\x01\x01:P\n" +
	"\x11OptionDBProcParam\x12\x1d.google.protobuf.FieldOptions\x18\xc6\xcf$ \x01(\bR\x11OptionDBProcParam\x88\x01\x01:H\n" +
	"\rOptionOldName\x12\x1d.google.protobuf.FieldOptions\x18\xc7\xcf$ \x01(\tR\rOptionOldName\x88\x01\x01:D\n" +
	"\vOptionTable\x12\x1d.google.protobuf.FieldOptions\x18\xc8\xcf$ \x01(\tR\vOptionTable\x88\x01\x01:P\n" +
	"\x11OptionBackUpTabel\x12\x1d.google.protobuf.FieldOptions\x18\xc9\xcf$ \x01(\tR\x11OptionBackUpTabel\x88\x01\x01B2H\x01Z.github.com/luyuancpp/protooption;messageoptionb\x06proto3"

var (
	file_proto_option_proto_rawDescOnce sync.Once
	file_proto_option_proto_rawDescData []byte
)

func file_proto_option_proto_rawDescGZIP() []byte {
	file_proto_option_proto_rawDescOnce.Do(func() {
		file_proto_option_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_option_proto_rawDesc), len(file_proto_option_proto_rawDesc)))
	})
	return file_proto_option_proto_rawDescData
}

var file_proto_option_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_option_proto_goTypes = []any{
	(NodeType)(0),                       // 0: NodeType
	(OPERATE_TYPE)(0),                   // 1: OPERATE_TYPE
	(BS_RESULT_TYPE)(0),                 // 2: BS_RESULT_TYPE
	(*descriptorpb.FileOptions)(nil),    // 3: google.protobuf.FileOptions
	(*descriptorpb.ServiceOptions)(nil), // 4: google.protobuf.ServiceOptions
	(*descriptorpb.MessageOptions)(nil), // 5: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 6: google.protobuf.FieldOptions
}
var file_proto_option_proto_depIdxs = []int32{
	3,  // 0: OptionFileDefaultNode:extendee -> google.protobuf.FileOptions
	4,  // 1: OptionIsPlayerService:extendee -> google.protobuf.ServiceOptions
	4,  // 2: OptionIsClientProtocolService:extendee -> google.protobuf.ServiceOptions
	5,  // 3: OptionTableId:extendee -> google.protobuf.MessageOptions
	5,  // 4: OptionTableName:extendee -> google.protobuf.MessageOptions
	5,  // 5: OptionPrimaryKey:extendee -> google.protobuf.MessageOptions
	5,  // 6: OptionForeignKey:extendee -> google.protobuf.MessageOptions
	5,  // 7: OptionForeignReferences:extendee -> google.protobuf.MessageOptions
	5,  // 8: OptionAutoIncrementKey:extendee -> google.protobuf.MessageOptions
	5,  // 9: OptionBackupTableName:extendee -> google.protobuf.MessageOptions
	5,  // 10: OptionLoadOnly:extendee -> google.protobuf.MessageOptions
	5,  // 11: OptionProcedureName:extendee -> google.protobuf.MessageOptions
	5,  // 12: OptionProcedureResult:extendee -> google.protobuf.MessageOptions
	5,  // 13: OptionIndex:extendee -> google.protobuf.MessageOptions
	5,  // 14: OptionUniqueKey:extendee -> google.protobuf.MessageOptions
	5,  // 15: OptionIsPlayerDatabase:extendee -> google.protobuf.MessageOptions
	5,  // 16: OptionOperateType:extendee -> google.protobuf.MessageOptions
	5,  // 17: OptionBaseAttributeSync:extendee -> google.protobuf.MessageOptions
	5,  // 18: OptionDeltaAttributeSync:extendee -> google.protobuf.MessageOptions
	6,  // 19: OptionRepeatLimit:extendee -> google.protobuf.FieldOptions
	6,  // 20: OptionDBFieldExtra:extendee -> google.protobuf.FieldOptions
	6,  // 21: OptionDBReadOnly:extendee -> google.protobuf.FieldOptions
	6,  // 22: OptionDBNamePrefix:extendee -> google.protobuf.FieldOptions
	6,  // 23: OptionDBLoadSql:extendee -> google.protobuf.FieldOptions
	6,  // 24: OptionDBNeedEscape:extendee -> google.protobuf.FieldOptions
	6,  // 25: OptionDBProcParam:extendee -> google.protobuf.FieldOptions
	6,  // 26: OptionOldName:extendee -> google.protobuf.FieldOptions
	6,  // 27: OptionTable:extendee -> google.protobuf.FieldOptions
	6,  // 28: OptionBackUpTabel:extendee -> google.protobuf.FieldOptions
	0,  // 29: OptionFileDefaultNode:type_name -> NodeType
	1,  // 30: OptionOperateType:type_name -> OPERATE_TYPE
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	29, // [29:31] is the sub-list for extension type_name
	0,  // [0:29] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_option_proto_init() }
func file_proto_option_proto_init() {
	if File_proto_option_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_option_proto_rawDesc), len(file_proto_option_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 29,
			NumServices:   0,
		},
		GoTypes:           file_proto_option_proto_goTypes,
		DependencyIndexes: file_proto_option_proto_depIdxs,
		EnumInfos:         file_proto_option_proto_enumTypes,
		ExtensionInfos:    file_proto_option_proto_extTypes,
	}.Build()
	File_proto_option_proto = out.File
	file_proto_option_proto_goTypes = nil
	file_proto_option_proto_depIdxs = nil
}
